Prototype 3
oresat/oresat-solar-simulator pull request #1
Opened 2023-06-02 17:48 UTC by ajm27pdx

Moving p3 validation into main branch

2023-06-04 19:08 UTC, ryanpdx requested changes
This is a little hard to review as there is no documentation.

Please fill put the README.md with high level overview of how it work, how to setup environment to for the project, and how to run the project. Also recommend adding mermaid diagram to the readme to show data flow between hardware and software as well as the server/client dataflow.

Please add docstring to all functions.

Also add `pyproject.toml` (has all the metadata for the project) and `requirements.txt` (used by developers to quickly install all dev dependencies) files. See the oresat-c3-software repo for examples.

What are 3 multiple prototype directories? There should be one source directory, called something like `oresat_solar_simulator`.

2023-06-04 19:08 UTC, ryanpdx commented on prototyping/prototype-3/p3-server.py
> +        assert False, "unhandled option"
Use argparse for this

2023-06-04 19:08 UTC, ryanpdx commented on prototyping/prototype-2/server.conf
I would be better to use standard configure file format like `.conf`.

2023-06-12 21:30 UTC, ajm27pdx commented on prototyping/prototype-3/p3-server.py
> +        assert False, "unhandled option"
Done! Much easier.

2023-06-12 21:30 UTC, ajm27pdx commented on prototyping/prototype-2/server.conf
This was a bit of a test implementation, I've switched to JSON conf files for the current version.

2023-06-12 21:34 UTC, ajm27pdx commented
Added `requirements.txt` and will finish building out `pyproject.toml` for final version clean up

2023-06-12 21:35 UTC, merged